/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSellIndexRouteImport } from './routes/_authenticated/sell.index'
import { Route as AuthenticatedSellOrdersRouteImport } from './routes/_authenticated/sell.orders'
import { Route as AuthenticatedSellProductsRouteImport } from './routes/_authenticated/sell.products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellIndexRoute = AuthenticatedSellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellOrdersRoute = AuthenticatedSellOrdersRouteImport.update({
  id: '/sell/orders',
  path: '/sell/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellProductsRoute =
  AuthenticatedSellProductsRouteImport.update({
    id: '/sell/products',
    path: '/sell/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/sell/orders': typeof AuthenticatedSellOrdersRoute
  '/sell/products': typeof AuthenticatedSellProductsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/sell/': typeof AuthenticatedSellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/sell/orders': typeof AuthenticatedSellOrdersRoute
  '/sell/products': typeof AuthenticatedSellProductsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/sell': typeof AuthenticatedSellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/_authenticated/sell/orders': typeof AuthenticatedSellOrdersRoute
  '/_authenticated/sell/products': typeof AuthenticatedSellProductsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/sell/': typeof AuthenticatedSellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/checkout'
    | '/orders'
    | '/product/$id'
    | '/seller/$id'
    | '/sell/orders'
    | '/sell/products'
    | '/admin/'
    | '/sell/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/checkout'
    | '/orders'
    | '/product/$id'
    | '/seller/$id'
    | '/sell/orders'
    | '/sell/products'
    | '/admin'
    | '/sell'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/_authenticated/checkout'
    | '/_authenticated/orders'
    | '/product/$id'
    | '/seller/$id'
    | '/_authenticated/sell/orders'
    | '/_authenticated/sell/products'
    | '/_authenticated/admin/'
    | '/_authenticated/sell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ChooseRoleRoute: typeof ChooseRoleRoute
  ProductIdRoute: typeof ProductIdRoute
  SellerIdRoute: typeof SellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell/': {
      id: '/_authenticated/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof AuthenticatedSellIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell/orders': {
      id: '/_authenticated/sell/orders'
      path: '/sell/orders'
      fullPath: '/sell/orders'
      preLoaderRoute: typeof AuthenticatedSellOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell/products': {
      id: '/_authenticated/sell/products'
      path: '/sell/products'
      fullPath: '/sell/products'
      preLoaderRoute: typeof AuthenticatedSellProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedSellOrdersRoute: typeof AuthenticatedSellOrdersRoute
  AuthenticatedSellProductsRoute: typeof AuthenticatedSellProductsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedSellIndexRoute: typeof AuthenticatedSellIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedSellOrdersRoute: AuthenticatedSellOrdersRoute,
  AuthenticatedSellProductsRoute: AuthenticatedSellProductsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedSellIndexRoute: AuthenticatedSellIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ChooseRoleRoute: ChooseRoleRoute,
  ProductIdRoute: ProductIdRoute,
  SellerIdRoute: SellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
